# VI Anhang {-}


# Studienpfade
Je nach Lernziel, Zeit und Interessen bieten sich unterschiedliche Studienpfade durch dieses Buch an. Im folgenden sind einige aufgez채hlt - untergliedert nach Fachrichtung, Vorerfahrung und Zeit.


## konsequtiver Master of Science in Wirtschaftspsychologie

Anahmen: 

- Zeitumfang: 44 UE f체r Lehre

- Vorerfahrung: Deskriptive Statistik, Inferenzstatistik, Grundlagen R, Grundlagen Visualisierung


Termin    Thema                               Kommentar
-------   ------                              ----------
1         Organisatorisches
          Einf체hrung
          Rahmen
2         Daten einlesen und aufbereiten
3         Daten visualisieren
4         Fallstudie
5         Inferenzstatistik                   kurze Wiederholung
          Daten modellieren               
6         Lineare Regression                  Wiederholung und Vertiefung
7         klassifizierende Regression
8         Baumbasierte Verfahren
9         Wahlfplichtthema                    Clusteranalyse, Dimensionsreduktion, Textmining, RMarkdown
10        Fallstudie
11        Wiederholung und Zusammenfassung
          
Die einzelnen Kapitel sind dabei nicht umfassend abzuarbeiten. Der Lehrende/ Lernende kann hier eine Auswahl treffen. Teilweise ist der Stoff eines Kapitels - ja nach Vorerfahrung der Lernenden - zu viel f체r einen Termin (mit jeweils 4 UE).

