---
title: "Folien für das Modul 'Praxis der Datenanalyse'"
#author: "ses"
#institute: "FOM" 
date: "WS17"
linkcolor: blue
urlcolor: blue
lang: de-De
output:
  beamer_presentation:
    fig_caption: no
    slide_level: 2
    includes:
        in_header: "Rahmen.tex" 
---



```{r setup, include=FALSE}
library(knitr)

knitr::opts_chunk$set(
    echo = TRUE,
    background='#E0E0E0',
#   fig.keep="none",
    out.width="80%",
#   cache = TRUE,
    tidy=TRUE,
    fig.align = "center",
    width.cutoff=70,
    fig.asp = .61,
    message = FALSE,
    warning = FALSE
)

options(width = 73)


```


```{r libs, include = FALSE, echo = FALSE}
#library(mosaic)
library(tidyverse)
library(formatR)
library(knitr)
library(gridExtra)
library(broom)
library(grid)
library(modelr)
library(viridis)
library(SDMTools)  # Güte von Klassifikationsmodellen
library(pROC)  # für ROC- und AUC-Berechnung
library(BaylorEdPsych)  # Pseudo-R-Quadrat
library(pander)
library(cluster)
library(psych)
library(stringr)  # Textverarbeitung
library(tidytext)  # Textmining
library(pdftools)  # PDF einlesen
library(downloader)  # Daten herunterladen
library(lsa)  # Stopwörter 
library(SnowballC)  # Wörter trunkieren
library(wordcloud)  # Wordcloud anzeigen
```



## Introducing Pipe-Syntax

Vergleichen Sie mal diese Syntax

```{r eval = FALSE}
filter(summarise(group_by(filter(stats_test, 
       !is.na(score)), interest), mw = mean(score)), 
       mw > 30)
```


