```{r include=FALSE, cache=FALSE}
set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  collapse = TRUE,
  cache = TRUE,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold"
)

```


# VI Anhang {-}


# Studienpfade
Je nach Lernziel, Zeit und Interessen bieten sich unterschiedliche Studienpfade durch dieses Buch an. Im folgenden sind einige aufgez채hlt - untergliedert nach Fachrichtung, Vorerfahrung und Zeit.


## Master of Science in Wirtschaftspsychologie und Consulting (MWPC)

Anahmen: 

- Zeitumfang: 44 UE f체r Lehre

- Vorerfahrung: Deskriptive Statistik, Inferenzstatistik, Grundlagen R, Grundlagen Visualisierung


Termin    Thema/ Kapitel                      
-------   --------------------------------------                              
1         Organisatorisches
          Einf체hrung
          Rahmen
          Daten einlesen
2         Datenjudo
3         Daten visualisieren
4         Fallstudie
5         Daten modellieren     
          Der p-Wert
6         Lineare Regression - Grundlagen
7         Lineare Regression - Vertiefung
8         Fallstudie
9         Textmining
10        Clusteranalyse
11        Wiederholung

          
Die einzelnen Kapitel sind dabei nicht umfassend abzuarbeiten. Der Lehrende/ Lernende kann hier eine Auswahl treffen. Teilweise ist der Stoff eines Kapitels - ja nach Vorerfahrung der Lernenden - zu viel f체r einen Termin (mit jeweils 4 UE).

