```{r include=FALSE, cache=FALSE}
set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  collapse = TRUE,
  cache = TRUE,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold"
)

```


# Prüfungshinweise


- Die Prüfung besteht aus zwei Teilen
    - einer Klausur (50% der Teilnote)
    - einer Datenanalyse (50% der Teilnote).
   
   
   
*Prüfungsrelevant* ist der gesamte Stoff aus dem Skript und dem Unterricht mit folgenden Ausnahmen:

  - Inhalte/Abschnitte, die als "nicht klausurrelevant" gekennzeichnet sind,
  - Inhalte/Abschnitte, die als "Vertiefung" gekennzeichnet sind,
  - Fallstudien (nur für Klausuren nicht prüfungslevant),
  - die Inhalte von Links,
  - die Inhalte von Fußnoten.
  
  
  
  
  
  
## Klausur

- Die Klausur besteht fast oder komplett aus Multiple-Choice (MC-)-Aufgaben mit mehreren Antwortoptionen; zumeist ist eine Antwort aus vieren auszuwählen.

- Die (maximale) Anzahl der richtigen Aussagen ist pro Aufgabe angegeben. Werden mehr Aussagen als "richtig" angekreuzt als angegeben, so wird die Aufgabe mit 0 Punkten beurteilt. Ansonsten werden Teilpunkte für jede Aufgabe vergeben.

- Jede Aussage gilt ceteris paribus (unter sonst gleichen Umständen). Aussagen der Art "A ist B" (z.B. "Menschen sind sterblich") sind *nur* dann als richtig auszuwählen, wenn die Aussage *immer* richtig ist.

- Im Zweifel ist eine Aussage auf den Stoff, so wie im Unterricht behandelt, zu beziehen.
Werden in Aussagen Zahlen abgefragt, so sind Antworten auch dann richtig, wenn die vorgeschlagene Antwort ab der 1. Dezimale von der wahren Antwort abweicht (einigermaßen genaue Aussagen werden als richtig akzeptiert). Bei Fragen zu R-Syntax spielen Aspekte wie Enter-Taste o.ä. bei der Beantwortung der Frage keine Rolle; diese Aspekte dürfen zu ignorieren.

- Jede Aussage einer MC-Aufgabe ist entweder richtig oder falsch (aber nicht beides oder keines).

- Die MC-Aufgaben sind nur mit Kreuzen zu beantworten; Text wird bei der Korrektur nicht berücksichtigt.

- Bei Nachholklausuren gelten die selben Inhalte (inkl. Schwerpunkte) wie bei der Standard-Klausur, sofern nicht anderweitig angegeben.

- I.d.R. sind nur Klausurpapier und ein nicht-programmierbarer Taschenrechner als Hilfsmittel zulässig.

- Die Musterlösungen zu offenen Fragen sind elektronisch hinterlegt.


## Datenanalyse

- Wenden Sie die passenden, im Modul eingeführten statistischen Verfahren an.

- Werten Sie die Daten mit R aus; R-Syntax soll verwendet und im Hauptteil dokumentiert werden.

- In der Wahl des Datensatzes sind Sie frei, mit folgender Ausnahme: Im Unterricht besprochene Datensätze dürfen nicht als Prüfungsleistung eingereicht werden (vgl. Abschnitt \@ref(daten)).

- Der (Original-)Name des Datensatzes (sowie ggf. Link) ist bei der Anmeldung anzugeben. 

- Gruppenarbeiten sind nicht zulässig.

- Hat sich jemand schon für einen Datensatz angemeldet, so darf dieser Datensatz nicht mehr gewählt werden ("first come, first serve").

- Fundorte für Datensätze sind z.B. [hier](http://www.stat.ufl.edu/~winner/datasets.html), [hier](http://archive.ics.uci.edu/ml/datasets.html) und [hier](http://vincentarelbundock.github.io/Rdatasets/datasets.html); im Internet finden sich viele Datensätze^[Googeln Sie mal nach "open datasets" o.ä.].

- Schreiben Sie Ihre Ergebnisse in einer Ausarbeitung zusammen; der Umfang der Ausarbeitung umfasst ca. *1000-1500 Wörter* (nur Hauptteil; d.h. exklusive Deckblatt, Verzeichnisse, Anhang etc.).

- Untersuchen Sie 2-3 Hypothesen.

- Denken Sie daran, Name, Matrikelnummer, Modulname etc. anzugeben (Deckblatt). Bei der Gestaltung des Layout entscheiden Sie selbständig bitte nach Zweckmäßigkeit (und Ästhetik).

- Fügen Sie keine Erklärungen oder Definitionen von statistischen Verfahren an.
